export interface Employees {
    EmpId : number,
    EmployeeCode : string,
    EducationalQualification : string,
    role : string,
    grade : string,
    achievements : string,
    ProvideService : string,
    BranchId : string,
    CurrentOfferId : number,
    CreateDate : Date,
    DeleteDate : Date,
    UpdatedDate : Date,
    name : string,
    gender : string,
    dob : Date,
    address : string,
    ContactNumber : string,
    email : string
}
